import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Bootstrap from "@/components/Bootstrap";
import Aos from "@/components/Aos";

export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <Aos/> 
        {children}
        <Bootstrap/> 
      </body>
    </html>
  );
}
