import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Bootstrap from "@/components/Bootstrap";


export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Bootstrap/> 
      </body>
    </html>
  );
}
